export const NFLTeams = [
    { label: 'Arizona Cardinals', value: 'ARI' },
    { label: 'Atlanta Falcons', value: 'ATL' },
    { label: 'Baltimore Ravens', value: 'BAL' },
    { label: 'Buffalo Bills', value: 'BUF' },
    { label: 'Carolina Panthers', value: 'CAR' },
    { label: 'Chicago Bears', value: 'CHI' },
    { label: 'Cincinnati Bengals', value: 'CIN' },
    { label: 'Cleveland Browns', value: 'CLE' },
    { label: 'Dallas Cowboys', value: 'DAL' },
    { label: 'Denver Broncos', value: 'DEN' },
    { label: 'Detroit Lions', value: 'DET' },
    { label: 'Green Bay Packers', value: 'GB' },
    { label: 'Houston Texans', value: 'HOU' },
    { label: 'Indianapolis Colts', value: 'IND' },
    { label: 'Jacksonville Jaguars', value: 'JAX' },
    { label: 'Kansas City Chiefs', value: 'KC' },
    { label: 'Las Vegas Raiders', value: 'LV' },
    { label: 'Los Angeles Chargers', value: 'LAC' },
    { label: 'Los Angeles Rams', value: 'LAR' },
    { label: 'Miami Dolphins', value: 'MIA' },
    { label: 'Minnesota Vikings', value: 'MIN' },
    { label: 'New England Patriots', value: 'NE' },
    { label: 'New Orleans Saints', value: 'NO' },
    { label: 'New York Giants', value: 'NYG' },
    { label: 'New York Jets', value: 'NYJ' },
    { label: 'Philadelphia Eagles', value: 'PHI' },
    { label: 'Pittsburgh Steelers', value: 'PIT' },
    { label: 'San Francisco 49ers', value: 'SF' },
    { label: 'Seattle Seahawks', value: 'SEA' },
    { label: 'Tampa Bay Buccaneers', value: 'TB' },
    { label: 'Tennessee Titans', value: 'TEN' },
    { label: 'Washington Commanders', value: 'WAS' },
]

export const categories = [
    { label: 'Game Lines', value: 'Game Lines' },
    { label: 'TD Scorers', value: 'TD Scorers' },
    { label: 'Passing Props', value: 'Passing Props' },
    { label: 'Rushing Props', value: 'Rushing Props' },
    { label: 'Receiving Props', value: 'Receiving Props' },
    { label: 'D/ST Props', value: 'D/ST Props' },
    { label: 'Player Specials', value: 'Player Specials' },
    { label: '1st Drive', value: '1st Drive' },
    { label: '1st of Game', value: '1st of Game' },
    { label: 'Game Specials', value: 'Game Specials' },
    { label: 'Quarters', value: 'Quarters' },
    { label: 'Halves', value: 'Halves' },
    { label: 'Game Props', value: 'Game Props' },
    { label: 'Team Props', value: 'Team Props' },
    { label: 'Weekly Specials', value: 'Weekly Specials' },
    { label: 'Kickoff Specials', value: 'Kickoff Specials' },
    { label: 'DK Squares', value: 'DK Squares' },
    { label: 'Futures', value: 'Futures' },
    { label: 'Awards', value: 'Awards' },
    { label: 'Wins', value: 'Wins' },
]